name: Alerta ntfy

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificacion a ntfy
        run: |
          curl -H "Title: Nuevo push en main" \
               -d "Se subio codigo al repositorio ${{ github.repository }} por ${{ github.actor }}" \
               https://ntfy.sh/devops-itla
