name: Alerta ntfy

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificacion a ntfy
        run: |
          curl -H "Title: Hola Mundo - Elizabeth Peralta Victoriano" \
               -d "Se subio codigo a main en ${{ github.repository }}. Usuario: ${{ github.actor }}." \
               https://ntfy.sh/devops-itla
